environment:
  nodejs_version: '9'
cache:
  - '%LOCALAPPDATA%\Yarn -> appveyor.yml'
  - node_modules -> yarn.lock

install:
  - ps: Install-Product node $env:nodejs_version x64
  - yarn
test_script:
  - .\bin\run --help
  - yarn test

build: off
