environment:
  nodejs_version: '14'
cache:
  - '%LOCALAPPDATA%\Yarn -> appveyor.yml'
  - node_modules -> yarn.lock

install:
  - ps: Install-Product node $env:nodejs_version x64
  - yarn
  - yarn build

test_script:
  - .\bin\run --help

build: off
