import { AutocompleteBase } from '../../base';
export default class Create extends AutocompleteBase {
    static aliases: string[];
    static hidden: boolean;
    static description: string;
    private _commands?;
    private get bashSetupScriptPath();
    private get bashCommandsListPath();
    private get zshSetupScriptPath();
    private get fishSetupScriptPath();
    private get zshCompletionSettersPath();
    private get fishCompletionFunctionPath();
    private get skipEllipsis();
    private get envAnalyticsDir();
    private get envCommandsPath();
    private get bashSetupScript();
    private get zshSetupScript();
    private get completionDotsFunc();
    private get bashCommandsList();
    private get zshCompletionSetters();
    private get zshCommandsSetter();
    private get zshCommandsFlagsSetters();
    private get commands();
    run(): Promise<void>;
    private ensureDirs;
    private createFiles;
    private fishSetupScript;
    private genCmdPublicFlags;
    private genCmdWithDescription;
    private genZshCmdFlagsSetter;
    private genZshAllCmdsListSetter;
    private wantsLocalFiles;
}
