import { AutocompleteBase } from '../../base.js';
export default class Create extends AutocompleteBase {
    static aliases: string[];
    static hidden: boolean;
    static description: string;
    private _commands?;
    private get bashSetupScriptPath();
    private get bashCommandsListPath();
    private get zshSetupScriptPath();
    private get fishSetupScriptPath();
    private get zshCompletionSettersPath();
    private get fishCompletionFunctionPath();
    private get skipEllipsis();
    private get envAnalyticsDir();
    private get envCommandsPath();
    private get bashFunctionsDir();
    private get zshFunctionsDir();
    private get zshCompletionFunctionPath();
    private get bashCompletionFunctionPath();
    private get bashSetupScript();
    private get zshSetupScript();
    private get completionDotsFunc();
    private get bashCommandsList();
    private get zshCompletionSetters();
    private get zshCommandsSetter();
    private get zshCommandsFlagsSetters();
    private get commands();
    private get bashCompletionFunction();
    private get zshCompletionFunction();
    run(): Promise<void>;
    private ensureDirs;
    private createFiles;
    private fishSetupScript;
    private genCmdPublicFlags;
    private genCmdWithDescription;
    private genZshCmdFlagsSetter;
    private genZshAllCmdsListSetter;
    private wantsLocalFiles;
    private wantsLocalDirs;
}
